# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.confidence_value import ConfidenceValue  # noqa: F401,E501
from swagger_server import util


class CheckResponseField(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, possible_values: List[ConfidenceValue]=None, validation_result: ConfidenceValue=None):  # noqa: E501
        """CheckResponseField - a model defined in Swagger

        :param possible_values: The possible_values of this CheckResponseField.  # noqa: E501
        :type possible_values: List[ConfidenceValue]
        :param validation_result: The validation_result of this CheckResponseField.  # noqa: E501
        :type validation_result: ConfidenceValue
        """
        self.swagger_types = {
            'possible_values': List[ConfidenceValue],
            'validation_result': ConfidenceValue
        }

        self.attribute_map = {
            'possible_values': 'possible_values',
            'validation_result': 'validation_result'
        }

        self._possible_values = possible_values
        self._validation_result = validation_result

    @classmethod
    def from_dict(cls, dikt) -> 'CheckResponseField':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CheckResponseField of this CheckResponseField.  # noqa: E501
        :rtype: CheckResponseField
        """
        return util.deserialize_model(dikt, cls)

    @property
    def possible_values(self) -> List[ConfidenceValue]:
        """Gets the possible_values of this CheckResponseField.


        :return: The possible_values of this CheckResponseField.
        :rtype: List[ConfidenceValue]
        """
        return self._possible_values

    @possible_values.setter
    def possible_values(self, possible_values: List[ConfidenceValue]):
        """Sets the possible_values of this CheckResponseField.


        :param possible_values: The possible_values of this CheckResponseField.
        :type possible_values: List[ConfidenceValue]
        """

        self._possible_values = possible_values

    @property
    def validation_result(self) -> ConfidenceValue:
        """Gets the validation_result of this CheckResponseField.


        :return: The validation_result of this CheckResponseField.
        :rtype: ConfidenceValue
        """
        return self._validation_result

    @validation_result.setter
    def validation_result(self, validation_result: ConfidenceValue):
        """Sets the validation_result of this CheckResponseField.


        :param validation_result: The validation_result of this CheckResponseField.
        :type validation_result: ConfidenceValue
        """

        self._validation_result = validation_result
